// Real browser against the real Rust server; all state is disposable.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {spawn, execFileSync} = require('node:child_process');
const {createInterface} = require('node:readline');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const binary = path.resolve(process.env.EVERYWHERE_BINARY || 'target/debug/everywhere');
const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'everywhere-browser-'));
const state = path.join(temporary, 'state');
const root = path.join(temporary, 'files');
const report = path.resolve('browser-report');
fs.mkdirSync(root);
fs.mkdirSync(report, {recursive:true});
const run = (...args) => execFileSync(binary, args, {encoding:'utf8', timeout:20000}).trim();
let server, browser;
(async () => {
  run('init','--state',state);
  const token = run('management-token','--state',state);
  server = spawn(binary, ['manage','--state',state,'--listen','127.0.0.1:0'], {stdio:['ignore','pipe','pipe']});
  let serverError = '';
  server.stderr.on('data', chunk => { serverError += chunk.toString(); });
  const address = await new Promise((resolve,reject) => {
    const timer = setTimeout(()=>reject(new Error(`management did not start: ${serverError}`)),15000);
    const lines = createInterface({input:server.stdout});
    lines.on('line',line=>{if(line.startsWith('LISTEN ')){clearTimeout(timer);resolve(line.slice(7));}});
    server.once('exit',code=>{clearTimeout(timer);reject(new Error(`management exited ${code}: ${serverError}`));});
  });
  browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors = [];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`http://${address}`);
  await page.getByRole('heading',{name:'내 장비에 연결'}).waitFor();
  await page.screenshot({path:path.join(report,'login.png'),fullPage:true});
  await page.getByLabel('관리 토큰',{exact:true}).fill(token);
  await page.getByRole('button',{name:'연결하기 →',exact:true}).click();
  await page.locator('#workspace').waitFor({state:'visible'});
  await page.getByLabel('폴더 ID',{exact:true}).fill('photos');
  await page.getByLabel('이 컴퓨터의 전체 경로',{exact:true}).fill(root);
  await page.getByRole('button',{name:'폴더 등록 ＋',exact:true}).click();
  await page.getByRole('heading',{name:'photos',exact:true}).waitFor();
  assert.ok(fs.existsSync(path.join(root,'.everywhere-folder')));
  fs.writeFileSync(path.join(root,'note.txt'),'original browser content');
  await page.getByRole('button',{name:'변경 재검사',exact:true}).click();
  await page.getByRole('status').filter({hasText:'1개 변경 기록'}).waitFor();
  fs.writeFileSync(path.join(root,'note.txt'),'edited browser content');
  await page.getByRole('button',{name:'변경 재검사',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('.actions button').disabled);
  const history = JSON.parse(run('share-history','--state',state,'--folder','photos','--path','note.txt'));
  const original = history.find(r=>r.object_path && fs.readFileSync(r.object_path,'utf8')==='original browser content');
  assert.ok(original);
  page.once('dialog',dialog=>dialog.accept('note.txt'));
  await page.getByRole('button',{name:'이전 버전 복구',exact:true}).click();
  const revision = page.locator('.revision').filter({hasText:original.id});
  await revision.waitFor();
  page.once('dialog',dialog=>dialog.accept());
  await revision.getByRole('button',{name:'이 버전 복원',exact:true}).click();
  await page.locator('#details').waitFor({state:'hidden'});
  assert.equal(fs.readFileSync(path.join(root,'note.txt'),'utf8'),'original browser content');
  await page.screenshot({path:path.join(report,'dashboard.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile horizontal overflow');
  await page.screenshot({path:path.join(report,'mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'화면 잠금',exact:true}).click();
  await page.getByRole('heading',{name:'내 장비에 연결'}).waitFor();
  assert.equal(await page.locator('#folder-list').textContent(),'');
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(report,'result.json'),JSON.stringify({passed:true,checks:['login','real folder registration','scan','historical restore bytes','mobile layout','lock','no runtime errors']},null,2));
  console.log('Browser acceptance: login, folder creation, scan, historical restore, mobile layout and lock passed.');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{
  if(browser) await browser.close();
  if(server && server.exitCode===null) {
    server.kill('SIGINT');
    await new Promise(resolve=>{server.once('exit',resolve);setTimeout(()=>{server.kill('SIGKILL');resolve();},3000).unref();});
  }
  fs.rmSync(temporary,{recursive:true,force:true});
});
